version: "3.3"
services:
  app:
    image: 127.0.0.1:5000/weather
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - traefik
    entrypoint: ["npm", "start"]
  traefik:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
